package com.github.phillipkruger.jaxblib.example.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data @AllArgsConstructor @NoArgsConstructor
@XmlAccessorType(XmlAccessType.FIELD)
public class Crap {

    private String crap1;
    private String crap2;
    private String crap3;
    private String crap4;
    private String crap5;
    private String crap6;
    private String crap7;
    private String crap8;
    private String crap9;
    private String crap10;
    private String crap11;
    private String crap12;
    private String crap13;
    private String crap14;
    private String crap15;
    private String crap16;
    private String crap17;
    private String crap18;
    private String crap19;
    private String crap20;
    private String crap21;
    private String crap22;
    private String crap23;
    private String crap24;
    private String crap25;
    private String crap26;
    private String crap27;
    private String crap28;
    private String crap29;
    private String crap30;
    private String crap31;
    private String crap32;
    private String crap33;
    private String crap34;
    private String crap35;
    private String crap36;
    private String crap37;
    private String crap38;
    private String crap39;
    private String crap40;
    private String crap41;
    private String crap42;
    private String crap43;
    private String crap44;
    private String crap45;
    private String crap46;
    private String crap47;
    private String crap48;
    private String crap49;
    private String crap50;
    private String crap51;
    private String crap52;
    private String crap53;
    private String crap54;
    private String crap55;
    private String crap56;
    private String crap57;
    private String crap58;
    private String crap59;
    private String crap60;
    private String crap61;
    private String crap62;
    private String crap63;
    private String crap64;
    private String crap65;
    private String crap66;
    private String crap67;
    private String crap68;
    private String crap69;
    private String crap70;
    private String crap71;
    private String crap72;
    private String crap73;
    private String crap74;
    private String crap75;
    private String crap76;
    private String crap77;
    private String crap78;
    private String crap79;
    private String crap80;
    private String crap81;
    private String crap82;
    private String crap83;
    private String crap84;
    private String crap85;
    private String crap86;
    private String crap87;
    private String crap88;
    private String crap89;
    private String crap90;
    private String crap91;
    private String crap92;
    private String crap93;
    private String crap94;
    private String crap95;
    private String crap96;
    private String crap97;
    private String crap98;
    private String crap99;
    private String crap100;
    
}
